#!/usr/bin/env bash
# Generate the local go.work so builds resolve the family libraries from sibling
# checkouts instead of the module proxy. go.work is gitignored: CI must resolve
# go.mod on its own, which is why the filesystem replaces were removed.
#
#   ./scripts/dev-go-work.sh            # siblings at ../
#   FAMILY_ROOT=~/src ./scripts/dev-go-work.sh
#   rm go.work                          # go back to the pinned proxy versions
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
family_root="${FAMILY_ROOT:-$(cd "$repo_root/.." && pwd)}"

modules=(
  Open-Auth-Go
  Open-Client-Go
  Open-Job-Go
  Open-Tenant-Go
  Open-ClickHouse-Go
  Open-HTTP-Go
  Open-Logger-Go
)

missing=()
for m in "${modules[@]}"; do
  [[ -f "$family_root/$m/go.mod" ]] || missing+=("$m")
done
if ((${#missing[@]})); then
  echo "error: no go.mod in $family_root for: ${missing[*]}" >&2
  echo "Clone the missing repos, or set FAMILY_ROOT to the tree that holds them." >&2
  exit 1
fi

go_version="$(awk '/^go /{print $2; exit}' "$repo_root/go.mod")"

{
  echo "// Generated by scripts/dev-go-work.sh — local development only, not committed."
  echo "go $go_version"
  echo
  echo "use ("
  echo "	."
  for m in "${modules[@]}"; do
    echo "	$family_root/$m"
  done
  echo ")"
  echo
  # go.mod pins open-auth-go through a version replace (see the comment there).
  # A workspace member cannot also be replaced at all versions, so the override
  # has to name the exact version go.mod replaces.
  auth_version="$(awk '/^replace github.com\/TheGrimmChester\/open-auth-go /{print $NF}' "$repo_root/go.mod")"
  if [[ -n "$auth_version" ]]; then
    echo "replace github.com/TheGrimmChester/open-auth-go $auth_version => $family_root/Open-Auth-Go"
  fi
} > "$repo_root/go.work"

echo "wrote $repo_root/go.work (siblings from $family_root)"
